# Generated by Django 3.2.8 on 2021-10-13 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0004_auto_20211012_1611'),
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesanan',
            name='makanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesanan', to='makanan.makanan'),
        ),
    ]
