# Generated by Django 3.2.8 on 2021-10-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='cek',
            field=models.TextField(blank=True, null=True),
        ),
    ]
