# Generated by Django 3.2.8 on 2021-10-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0002_makanan_cek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makanan',
            name='cek',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='makanan',
            name='nama',
        ),
    ]
