# Generated by Django 3.2.8 on 2021-10-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0003_auto_20211012_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='makanan',
            name='jenis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makanan',
            name='nama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
