# Generated by Django 3.2.8 on 2021-10-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makanan', '0004_auto_20211012_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makanan',
            name='jenis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='makanan',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
